name: Deploy to GitHub Pages on PR
on: pull_request

permissions: 
  checks: write
  contents: read

jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: v22.13.0
      - uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: true
      - name: Build
        run: pnpm build

      # gh-pagesを使ってbuildファイルをdeploy
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

      # Vitest を使ってユニットテストを実行
      - name: Run Vitest
        run: pnpm test
        env: 
          CI: true